#!/usr/bin/env bash

command="$1"
case "$command" in
"" | "-h" | "--help" )
  echo -e "$(rubystrap-version)\n$(rubystrap-help)"
  ;;
"-v" | "--version" )
  exec rubystrap-version
  ;;
* )
  command_path="$(command -v "rubystrap-$command" || true)"
  if [ -z "$command_path" ]; then
    echo -e "$(rubystrap-version)\n$(rubystrap-help)"
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
