#!/usr/bin/env bash

SCRIPT_DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=$(dirname $SCRIPT_DIR)

if [ -z $CHEF_TARGET ]; then
  echo "Please provide a host to sync to:"
  echo "  CHEF_TARGET=root@192.168.50.100 ./sync"
  exit 1
fi

if [ $CHEF_DIR ]; then
  target_directory=$CHEF_DIR
else
  target_directory="~/chef"
fi

echo "Syncing $ROOT_DIR to $CHEF_TARGET:$target_directory"
rsync --delete --recursive --progress $ROOT_DIR/* $CHEF_TARGET:$target_directory

